version: "3.8"

services:
  app:
    image: abhiramkosuru/devops-demo:${APP_VERSION}
    container_name: devopsdemo
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_PROFILE: ${SPRING_PROFILE}
